" ============================== "
" General Options                "
" ============================== "
set title                              "Allows vim to change title of the terminal based on the  file.

set hlsearch                           "Highlights all occurrences of the current search pattern.
set ignorecase                         "Searches are case-insensitive.
set linebreak                          "Soft-wrapping, long lines are displayed as if they were broken.
set wrap
set smartcase                          "Case insensitive search if pattern contains no cased letters.
set smartindent                        "Automatically adjust indentation.

set modifiable

set number
set relativenumber
set numberwidth=1
set signcolumn=yes                    "Displays the signs column, if any.

set scrolloff=8                        "Minimum number of lines to keep above and below cursor.
set sidescrolloff=8                    "How much of the current line to keep visible on the sides.

set cmdheight=1
set laststatus=2                       "Displays the status bar.
set pumheight=10                       "Height of the pop up menu,
set showcmd
set showmode                           "Shows the mode vim is currently in.
set showtabline=2                      "Displays the tab bar.

set background=dark
if has(('termguicolors'))
    set termguicolors                  "Enables truecolor (256 colors).
endif
set colorcolumn=88                     "Highlights columns {...,80,88,...}.
set cursorcolumn                       "Highlights the current column being edited.
set cursorline                         "Highlights the current line being edited.

set expandtab                          "Expands all \tabs into spaces.
set tabstop=4                          "How many columns wide is each tab.
set shiftwidth=4                       "How many columns wide is each indentation.

set fileencoding=utf-8
set spell
set spelllang=en,es
set spellsuggest=10

set timeoutlen=150
set updatetime=50

" ============================== "
" Sane defaults                  "
" ============================== "
set nobackup                           "Stops vim from creating backup files, those with the '~' appended.
set noswapfile                         "Stops vim from creating swap files, those ending with \".swp\".
set undofile                           "Creates an undofile, literally the best way to recover.
set undodir=~/.vim/.undodir

if has(('clipboard'))
    set clipboard=unnamedplus          "Allows vim to use the system's clipboard.
endif

" ============================== "
" Completions and other stuff    "
" ============================== "
" This has to do with how completions are displayed... I think.
set completeopt=menu,preview,noselect

set virtualedit=all
set list
set showbreak=↪\
 set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·,space:·,eol:↴

" ============================== "
" vim cmds                       "
" ============================== "
syntax on

" ============================== "
" Plugins
" ============================== "
call plug#begin()
"Colorschemes"
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'dense-analysis/ale', { 'as' : 'ale' }
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npx --yes yarn install' }
Plug 'tomtom/tcomment_vim', { 'as': 'tcomment' }
Plug 'joshdick/onedark.vim', { 'as': 'onedark' }
Plug 'easymotion/vim-easymotion', { 'as' : 'easymotion' }
Plug 'vim-airline/vim-airline'
call plug#end()

filetype plugin indent on
" ============================= "
" Source files                  "
" ============================= "
source /home/$USER/.vim/autoload/plug.vim
source /home/$USER/.vim/autoload/keymaps.vim
source /home/$USER/.vim/ftplugin/ale.vim
source /home/$USER/.vim/ftplugin/easymotion.vim
silent! colorscheme onedark

command! -nargs=0 -bar WQ :wq
command! -nargs=0 -bar Wq :wq

 let g:airline#extensions#tabline#enabled = 1
